#!/bin/sh -e

if [ ! -d steamcmd ]; then
    (
        echo 'Downloading SteamCMD'
        mkdir steamcmd
        cd steamcmd
        curl --insecure https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz | tar xz
    )
fi

steamcmd/steamcmd.sh +login anonymous +force_install_dir csgo +app_update 740 +quit
csgo/srcds -game csgo -console -usercon +game_type 1 +game_mode 0 +mapgroup mg_armsrace +map ar_shoots
