#!/bin/sh -e

cd "$(dirname "$0")/.."

exec docker run \
    --rm -it \
    --name csgo \
    -p 27015:27015 \
    -p 27015:27015/udp \
    -v "$PWD/steam:/home/steam" \
    -v "$PWD/bin:/home/steam/bin" \
    steamcmd \
    "$@"
